######## Config ########
workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


rule all:
    input:
        "qc/multiqc",
        "qc/fastp/fastp.stats.tsv",
        expand("3LTR/{sample}.1.3ltr.fq", sample=config["samples"]),
        expand("3LTR/{sample}.2.3ltr.fq", sample=config["samples"]),


include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"
include: "rules/3ltr.smk"
