######## Config ########
workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


rule all:
    input:
        "qc/multiqc",
        "qc/fastp/fastp.stats.tsv",
        expand("map/{sample}.bam.stat", sample=config["samples"]),
        expand("map/{sample}.filter.bam.stat", sample=config["samples"]),
        expand("umi/{sample}.umi.json", sample=config["samples"]),
        expand("umi/{sample}.umi.html", sample=config["samples"]),
        expand("umi/{sample}.umi.bam.stat", sample=config["samples"]),
        expand("anno/{sample}.is.combine.tsv", sample=config["samples"]),
        expand("stats/{sample}.is.diversity.tsv", sample=config["samples"]),
        expand("stats/{sample}.top10_is.tsv", sample=config["samples"]),
        expand("stats/{sample}.top10_is.png", sample=config["samples"]),
        expand("stats/{sample}.chrom_dist.png", sample=config["samples"]),
        expand("stats/{sample}.effect_pie.png", sample=config["samples"]),
        expand("stats/{sample}.repclass_pie.png", sample=config["samples"]),


include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"
include: "rules/3ltr.smk"
include: "rules/map.smk"
include: "rules/umi.smk"
include: "rules/isite.smk"
include: "rules/anno.smk"
include: "rules/stats.smk"
