######## Config ########
workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


rule all:
    input:
        "qc/multiqc",
        "qc/fastp/fastp.stats.tsv",


include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"
